# Generated by Django 3.2 on 2021-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitas',
            name='csrf_cookie',
        ),
        migrations.AddField(
            model_name='visitas',
            name='sitio_web',
            field=models.CharField(default='', max_length=255),
        ),
    ]
