# Generated by Django 3.2 on 2021-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(choices=[('P', 'Peticiones'), ('Q', 'Quejas'), ('R', 'Reclamos'), ('S', 'Sugerencias')], default='Procedimiento', max_length=200, null=True, verbose_name='Procedimiento')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=200, verbose_name='Número de teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.BooleanField(default=False, verbose_name='Contestado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created'],
            },
        ),
    ]
